export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';

export const PURCHAE_BURGER_START = 'PURCHAE_BURGER_START';
export const PURCHAE_BURGER_SUCCESS = 'PURCHAE_BURGER_SUCCESS';
export const PURCHAE_BURGER_FAIL = 'PURCHAE_BURGER_FAIL';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const FETCH_ORDERS_START= 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS= 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED= 'FETCH_ORDERS_FAILED';

export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
export const AUTH_LOGOUT= 'AUTH_LOGOUT';
